In [4]:
import torch

print(torch.__version__)
print(torch.backends.mps.is_built())
print(torch.backends.mps.is_available())

2.7.1+cpu
False
False


In [8]:
import torch
from torch import nn
from torch import optim

In [9]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

In [10]:
model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [11]:
for epoch in range(10000):
    output = model(x)
    cost = criterion(output, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8819]], requires_grad=True), Parameter containing:
tensor([-0.4973], requires_grad=True)], Cost : 1.373
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8808]], requires_grad=True), Parameter containing:
tensor([-0.4741], requires_grad=True)], Cost : 1.373
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8801]], requires_grad=True), Parameter containing:
tensor([-0.4597], requires_grad=True)], Cost : 1.372
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8796]], requires_grad=True), Parameter containing:
tensor([-0.4507], requires_grad=True)], Cost : 1.372
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8794]], requires_grad=True), Parameter containing:
tensor([-0.4451], requires_grad=True)], Cost : 1.372
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8792]], requires_grad=True), Parameter containing:
tensor([-0.4417], requires_grad=True)], Cost : 1.372
Epoch : 7000, Model : [Parameter contain

In [ ]:
#데이터 세트와 데이터 로더

In [18]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 
 #데이터 세트와 데이터 로더는 torch.utils.data 모듈에 있다 

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [19]:
#데이터 세트와 데이터 로더 적용
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)
#배치크기 2 데이터순서 변경 셔플, 배치제거를 통해 배치크기에 맞지 않는 배치는 제거한다

In [20]:
#모델, 오차함수, 최적화(optimizer) 함수 정의
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)
#다중 선형 회귀도 선형 변환 클래스 , 


In [21]:
#데이터 로더 적용
for epoch in range(20000):
    cost = 0.0 #에포크 마다 오차를 다시 계산하기 위해 0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 1.0468, -0.2718],
        [ 0.5424,  0.6508]], requires_grad=True)], Cost : 0.047
Epoch : 2000, Model : [Parameter containing:
tensor([[ 1.1808, -0.3802],
        [ 0.6568,  0.5583]], requires_grad=True)], Cost : 0.030
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.2874, -0.4663],
        [ 0.7478,  0.4848]], requires_grad=True)], Cost : 0.019
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.3721, -0.5348],
        [ 0.8202,  0.4264]], requires_grad=True)], Cost : 0.012
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.4394, -0.5893],
        [ 0.8775,  0.3798]], requires_grad=True)], Cost : 0.007
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.4929, -0.6325],
        [ 0.9233,  0.3430]], requires_grad=True)], Cost : 0.005
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.5354, -0.6669],
        [ 0.9595,  0.3136]], requires_grad=True)], Cost : 0.003
Epoch : 8000, Model : [Parameter containi

In [ ]:
# 비선형 회귀 (모듈 클래스)

In [22]:
# 라이브러리 및 프레임워크 초기화
import torch
import pandas as pd #csv읽기위해 사용
from torch import nn #신경망(뉴럴네트워크) 모듈- 계층 , 활성화 함수, 손실함수, 와 같은 빌딩 블록 제공 
from torch import optim #최적화 옵티마이저 
from torch.utils.data import Dataset, DataLoader #데이터셋, 데이터 로

In [23]:
#사용자 정의 데이터 
class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x = df.iloc[:, 0].values
        self.y = df.iloc[:, 1].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x[index] ** 2, self.x[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y

    def __len__(self):
        return self.length

In [25]:
# 사용자 정의 모델(선형 변환)
class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(2, 1)

    def forward(self, x):
        x = self.layer(x)
        return x

In [27]:
import os
print(os.getcwd())

/home/jovyan/work/workplace/AIFFEL_quest_rs/Exploration/Quest01


In [30]:
#사용자 정의 데이터 세트와 데이터 로더
train_dataset = CustomDataset("/home/jovyan/work/workplace/AIFFEL_quest_rs/Exploration/Quest01/non_linear.csv")
train_dataloader = DataLoader(train_dataset, batch_size=128, shuffle=True, drop_last=True)

print(f"핫")

핫


In [31]:
#gpu 연산 적용
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.MSELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.0001)

In [32]:
#학습진행
for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 3.1170, -1.7008]], requires_grad=True), Parameter containing:
tensor([-0.5184], requires_grad=True)], Cost : 0.509
Epoch : 2000, Model : [Parameter containing:
tensor([[ 3.1158, -1.7020]], requires_grad=True), Parameter containing:
tensor([-0.4322], requires_grad=True)], Cost : 0.471
Epoch : 3000, Model : [Parameter containing:
tensor([[ 3.1138, -1.7023]], requires_grad=True), Parameter containing:
tensor([-0.3534], requires_grad=True)], Cost : 0.370
Epoch : 4000, Model : [Parameter containing:
tensor([[ 3.1131, -1.7022]], requires_grad=True), Parameter containing:
tensor([-0.2815], requires_grad=True)], Cost : 0.367
Epoch : 5000, Model : [Parameter containing:
tensor([[ 3.1117, -1.7024]], requires_grad=True), Parameter containing:
tensor([-0.2155], requires_grad=True)], Cost : 0.306
Epoch : 6000, Model : [Parameter containing:
tensor([[ 3.1109, -1.7026]], requires_grad=True), Parameter containing:
tensor([-0.1551], requires_grad=T

In [33]:
#모델 평가
with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor(
        [
            [1 ** 2, 1],
            [5 ** 2, 5],
            [11 ** 2, 11]
        ]
    ).to(device)
    outputs = model(inputs)
    print(outputs)


tensor([[  1.4434],
        [ 69.2059],
        [357.2833]])


In [41]:
save_dir = "./models"

In [42]:
if not os.path.exists(save_dir):
    os.makedirs(save_dir) # os.makedirs는 중간 경로가 없으면 모두 생성해줍니다.
    print(f"디렉토리 '{save_dir}'를 생성했습니다.")

디렉토리 './models'를 생성했습니다.


In [45]:
#모델 저장

torch.save(
    model,
    "./models/model.pt"
)



In [46]:
torch.save(
    model.state_dict(),
    "./models/model_state_dict.pt"
)

In [6]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())


2.7.1+cpu
False


In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0


In [1]:
import torch
print(f"PyTorch의 CUDA 버전: {torch.version.cuda}")

PyTorch의 CUDA 버전: None


In [ ]:
!git config --global user.email "nagujean.com"
!git config --global user.name "nagujean"

In [16]:
!git clone https://github.com/nagujean/AIFFEL_quest_rs.git

Cloning into 'AIFFEL_quest_rs'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 104 (delta 47), reused 29 (delta 7), pack-reused 0 (from 0)
Receiving objects: 100% (104/104), 1.93 MiB | 5.03 MiB/s, done.
Resolving deltas: 100% (47/47), done.


In [ ]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!pwd

/content


In [17]:
%cd AIFFEL_quest_rs

/content/AIFFEL_quest_rs/AIFFEL_quest_rs


In [25]:
%cd /content/

/content


In [26]:
!rm -rf AIFFEL_quest_rs/

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [28]:
%cd /content/drive/MyDrive/AIFFEL_quest_rs/

/content/drive/MyDrive/AIFFEL_quest_rs


In [1]:
!pwd

/home/jovyan/work/workplace/AIFFEL_quest_rs/Exploration/Quest01


In [ ]:
!git add .

In [22]:
!git add .
!git commit -m " 코랩에서 colab_test.ipynb 파일 생성 테스트"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [1]:
!git add .

In [3]:
!git status

On branch main
Your branch is behind 'origin/main' by 8 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   colab_test.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [4]:
!git config --global user.email "nagujean@gmail.com"
!git config --global user.name "nagujean"

In [5]:
!git commit -m "파이토치 테스트 모델 파일등 업뎃"

[main 36ba7b3] 파이토치 테스트 모델 파일등 업뎃
 5 files changed, 1319 insertions(+), 1 deletion(-)
 create mode 100644 Exploration/Quest01/.ipynb_checkpoints/colab_test-checkpoint.ipynb
 create mode 100644 Exploration/Quest01/models/model.pt
 create mode 100644 Exploration/Quest01/models/model_state_dict.pt
 create mode 100644 Exploration/Quest01/non_linear.csv


In [6]:
!git push origin main

Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 2 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 9.66 KiB | 2.42 MiB/s, done.
Total 10 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/nagujean/AIFFEL_quest_rs.git
   c903d55..36ba7b3  main -> main


In [4]:
!git pull origin main

From https://github.com/nagujean/AIFFEL_quest_rs
 * branch            main       -> FETCH_HEAD
Updating 36ba7b3..0cee8da
error: Your local changes to the following files would be overwritten by merge:
	Exploration/Quest01/colab_test.ipynb
Please commit your changes or stash them before you merge.
Aborting


In [ ]:
!git stas